# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-06 12:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datalayer', '0003_auto_20170606_2229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rental_listings',
            old_name='has_embedded_video1',
            new_name='has_embedded_video',
        ),
        migrations.RenameField(
            model_name='rental_listings',
            old_name='has_gallery1',
            new_name='has_gallery',
        ),
        migrations.RenameField(
            model_name='rental_listings',
            old_name='is_bold1',
            new_name='is_bold',
        ),
        migrations.RenameField(
            model_name='rental_listings',
            old_name='is_boosted1',
            new_name='is_boosted',
        ),
        migrations.RenameField(
            model_name='rental_listings',
            old_name='is_classified1',
            new_name='is_classified',
        ),
        migrations.RenameField(
            model_name='rental_listings',
            old_name='is_featured1',
            new_name='is_featured',
        ),
        migrations.RenameField(
            model_name='rental_listings',
            old_name='is_highlighted1',
            new_name='is_highlighted',
        ),
        migrations.RenameField(
            model_name='rental_listings',
            old_name='is_super_featured1',
            new_name='is_super_featured',
        ),
    ]
