# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-06 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalayer', '0004_auto_20170606_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental_listings',
            name='agency_reference',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='rental_listings',
            name='easting',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rental_listings',
            name='latitude',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rental_listings',
            name='longitude',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rental_listings',
            name='northing',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
