# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-06 12:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datalayer', '0005_auto_20170606_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental_listings',
            name='data_source',
        ),
    ]
