# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-06 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalayer', '0006_remove_rental_listings_data_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental_listings',
            name='id_agency_tm',
            field=models.IntegerField(db_column='id_agency_tm', default=0),
            preserve_default=False,
        ),
    ]
