# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-06 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalayer', '0007_auto_20170606_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental_listings',
            name='id_agency_tm',
            field=models.IntegerField(db_column='id_agency_tm', null=True),
        ),
    ]
