# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-07 01:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalayer', '0008_auto_20170606_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental_photo',
            name='id_rental_listing',
            field=models.IntegerField(db_column='id_rental_listing'),
        ),
    ]
