# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-13 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalayer', '0011_auto_20170613_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental_listings',
            name='note_date',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
