# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-15 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalayer', '0013_auto_20170614_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental_listings',
            name='rent_per_week',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rental_listings',
            name='start_price',
            field=models.IntegerField(null=True),
        ),
    ]
